project:
  type: book

book:
  title: "Biostatistics with R"
  author: "Corneille Ntihabose"

  chapters:
    - index.qmd
    - 01-overview.qmd
    - 02-overview-github.qmd
    - 03-types-of-data.qmd
    - 04-descriptive-statistics.qmd
    - 05-probability-distributions.qmd
    - 06-inferential-statistics.qmd
    - 07-study-designs-sampling.qmd
    - 08-epidemiological-measures.qmd
    - 09-statistical-tests.qmd
    - 10-regression.qmd
    - 11-survival-analysis.qmd
    - 12-diagnostic-tests.qmd
    - 13-missing-data.qmd
    - 14-reporting-results.qmd
    - 15-reproducible-research.qmd

  sidebar:
    style: docked
    background: light

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true